### ISSUE TITLE
Function Flow

### ISSUE THREAD

**Issue by RobertIndie** [FunctionStream/function-stream#95]
## Frontend

- [x] #100
- [ ] #103
- [ ] #108
- [ ] Some Function image component for testing
- [ ] Generation for the deploy definition
- [ ] Context menu

## Backend

- [x] #97
- [x] #98
- - [x] Deploy definition parser
- - [x] K8s connector
- - [x] REST handler
- [ ] #112
- [ ] #113
- [ ] Function example images
